(ns ol.vips.codegen
  (:require
   [clojure.java.io :as io]
   [clojure.pprint :as pprint]
   [clojure.string :as str]
   [ol.vips :as v]
   [ol.vips.impl.introspect :as introspect]))

(set! *warn-on-reflection* true)

(def ^:private generated-banner
  ";; Copyright (c) 2026 Casey Link <casey@outskirtslabs.com>\n;; SPDX-License-Identifier: EUPL-1.2\n;; Generated by `bb gen`. Do not edit by hand.\n\n")

(def ^:private clojure-core-symbols
  (->> (ns-publics 'clojure.core)
       keys
       (map (comp symbol name))
       set))

(def ^:private supported-primitive-kinds
  #{:string :boolean :int :uint :long :int64 :uint64 :double :enum :flags})

(defn- kebab-name
  [value]
  (-> value
      (str/replace "_" "-")
      (str/replace #"([a-z0-9])([A-Z])" "$1-$2")
      str/lower-case))

(defn- operation-id
  [operation-name]
  (-> operation-name kebab-name keyword))

(defn- enum-id
  [type-name]
  (-> type-name
      (str/replace #"^Vips" "")
      kebab-name
      keyword))

(defn- local-name
  [arg-name]
  (let [value (kebab-name arg-name)]
    (case value
      "in" "input"
      "fn" "fn-value"
      value)))

(defn- symbol-name
  [value]
  (symbol (local-name value)))

(defn- enum-reference
  [type-name]
  (str "ol.vips.enums/" (name (enum-id type-name))))

(defn- image-type?
  [{:keys [value-type]}]
  (= "VipsImage" value-type))

(defn- image-seq-type?
  [{:keys [value-type]}]
  (= "VipsArrayImage" value-type))

(defn- float-seq-type?
  [{:keys [value-type]}]
  (= "VipsArrayDouble" value-type))

(defn- supported-input?
  [{:keys [kind] :as arg}]
  (case kind
    :object (image-type? arg)
    :boxed (or (image-seq-type? arg)
               (float-seq-type? arg))
    (contains? supported-primitive-kinds kind)))

(defn- supported-output?
  [{:keys [kind] :as arg}]
  (case kind
    :object (image-type? arg)
    (contains? supported-primitive-kinds kind)))

(defn- public-type
  [{:keys [kind value-type]}]
  (cond
    (= kind :object)
    {:kind  :image
     :label "image"}

    (= kind :boxed)
    (cond
      (= value-type "VipsArrayImage")
      {:kind  :image-seq
       :label "seqable of image"}

      (= value-type "VipsArrayDouble")
      {:kind  :float-seq
       :label "seqable of number"}

      :else
      {:kind  :unknown
       :label "value"})

    (= kind :string)
    {:kind  :string
     :label "string"}

    (= kind :boolean)
    {:kind  :boolean
     :label "boolean"}

    (contains? #{:int :uint :long :int64 :uint64} kind)
    {:kind  :integer
     :label "integer"}

    (= kind :double)
    {:kind  :float
     :label "float"}

    (= kind :enum)
    {:kind      :enum
     :label     "keyword"
     :enum-id   (enum-id value-type)
     :reference (enum-reference value-type)}

    (= kind :flags)
    {:kind  :flags
     :label "integer flags"}

    :else
    {:kind  :unknown
     :label "value"}))

(defn- public-arg-spec
  [{:keys [name blurb] :as arg}]
  {:name  name
   :blurb blurb
   :type  (public-type arg)})

(defn- input-args
  [operation]
  (->> (:args operation)
       (filter :input?)
       vec))

(defn- output-args
  [operation]
  (->> (:args operation)
       (filter :output?)
       vec))

(defn- required-inputs
  [operation]
  (->> (input-args operation)
       (filter :required?)
       vec))

(defn- optional-inputs
  [operation]
  (->> (input-args operation)
       (remove :required?)
       (filter supported-input?)
       vec))

(defn- operation-supported?
  [operation]
  (and (every? supported-input? (required-inputs operation))
       (every? supported-output? (output-args operation))))

(defn- operation-spec
  [operation]
  (let [required-inputs* (required-inputs operation)
        optional-inputs* (optional-inputs operation)
        outputs*         (output-args operation)]
    {:id              (operation-id (:name operation))
     :operation-name  (:name operation)
     :description     (:description operation)
     :required-inputs (mapv public-arg-spec required-inputs*)
     :optional-inputs (mapv public-arg-spec optional-inputs*)
     :outputs         (mapv public-arg-spec outputs*)}))

(defn- enum-spec
  [type-name]
  (let [enum (introspect/describe-enum type-name)]
    (assoc (select-keys enum [:type-name :keyword->value :value->keyword])
           :id (enum-id type-name)
           :values (-> enum :keyword->value keys sort vec))))

(defn- arg-doc-line
  [{:keys [name blurb type]}]
  (let [{:keys [label reference]} type
        type-label                (if reference
                                    (format "%s, see `%s`" label reference)
                                    label)]
    (format "- `%s` -> `:%s` (%s): %s"
            (local-name name)
            name
            type-label
            blurb)))

(defn- indent-docstring
  [text]
  (->> (str/split text #"\n" -1)
       (map-indexed (fn [index line]
                      (if (zero? index)
                        line
                        (str "  " line))))
       (str/join "\n")))

(defn- operation-docstring
  [{:keys [operation-name description required-inputs optional-inputs outputs]}]
  (let [returns-line
        (cond
          (and (= 1 (count outputs))
               (= "out" (:name (first outputs)))
               (= :image (get-in (first outputs) [:type :kind])))
          "Returns an image handle.\n\n"

          (contains? (set (map :name outputs)) "out")
          "Returns a closeable result map. Pass it anywhere an image is expected, or inspect `:out` and the additional outputs directly.\n\n"

          :else
          "Returns a result map.\n\n")]
    (indent-docstring
     (str description
          "\n\n"
          "Operation name: `" operation-name "`.\n\n"
          returns-line
          "Required inputs:\n"
          (if (seq required-inputs)
            (str/join "\n" (map arg-doc-line required-inputs))
            "- none")
          "\n\n"
          "Optional inputs:\n"
          (if (seq optional-inputs)
            (str/join "\n" (map arg-doc-line optional-inputs))
            "- none")
          "\n\n"
          "Outputs:\n"
          (if (seq outputs)
            (str/join "\n" (map arg-doc-line outputs))
            "- none")))))

(defn- operation-source
  [{:keys [id] :as spec}]
  (let [fn-name       (with-meta (symbol (name id))
                        {:generated      true
                         :operation-name (:operation-name spec)})
        required-syms (mapv (comp symbol-name :name) (:required-inputs spec))
        opts-sym      (symbol "opts")
        required-map  (into {}
                            (map (fn [{:keys [name]}]
                                   [(keyword name) (symbol-name name)]))
                            (:required-inputs spec))
        docstring     (-> (pr-str (operation-docstring spec))
                          (str/replace "\\n" "\n"))
        self-call     (str "("
                           (name fn-name)
                           (when (seq required-syms)
                             (str " " (str/join " " (map str required-syms))))
                           " {})")
        base-call     (str "(v/call "
                           (pr-str (:operation-name spec))
                           " "
                           (pr-str required-map)
                           ")")
        merged-call   (str "(v/call "
                           (pr-str (:operation-name spec))
                           " "
                           "(clojure.core/merge "
                           (pr-str required-map)
                           " opts))")]
    (if (seq (:optional-inputs spec))
      (str "(defn " (name fn-name) "\n"
           "  " docstring "\n"
           "  (" (pr-str (vec required-syms)) " " self-call ")\n"
           "  (" (pr-str (vec (conj required-syms opts-sym))) "\n"
           "   " merged-call "))")
      (str "(defn " (name fn-name) "\n"
           "  " docstring "\n"
           "  " (pr-str (vec required-syms)) "\n"
           "  " base-call ")"))))

(defn- emit-forms!
  [path forms]
  (io/make-parents path)
  (with-open [^java.io.Writer writer (io/writer path)]
    (.write writer ^String generated-banner)
    (binding [*out*                       writer
              *print-namespace-maps*      false
              pprint/*print-right-margin* 100]
      (doseq [form forms]
        (if (string? form)
          (do
            (.write writer ^String form)
            (newline)
            (newline))
          (do
            (pprint/pprint form)
            (newline))))))
  (spit path
        (-> (slurp path)
            (str/replace "\\n" "\n"))))

(defn- registry-source
  [registry]
  (str "(def registry\n"
       "  {\n"
       (str/join "\n"
                 (map (fn [[k v]]
                        (str "   " (pr-str k) " " (pr-str v)))
                      registry))
       "\n  })"))

(defn- refer-clojure-exclude-clause
  [symbols]
  (let [excluded (->> symbols
                      (filter clojure-core-symbols)
                      distinct
                      sort
                      vec)]
    (when (seq excluded)
      (list :refer-clojure :exclude excluded))))

(defn- load-operation-infos
  []
  (reduce (fn [{:keys [operations skipped]} operation-name]
            (try
              {:operations (conj operations (v/operation-info operation-name))
               :skipped    skipped}
              (catch clojure.lang.ExceptionInfo ex
                (if (= "Unknown libvips operation" (ex-message ex))
                  {:operations operations
                   :skipped    (conj skipped operation-name)}
                  (throw ex)))))
          {:operations []
           :skipped    []}
          (v/operations)))

(defn- enum-forms
  [enum-specs]
  (let [registry       (into (sorted-map) (map (juxt :id identity) enum-specs))
        enum-symbols   (map (comp symbol name :id) enum-specs)
        exclude-clause (refer-clojure-exclude-clause enum-symbols)
        ns-form        (list* 'ns
                              'ol.vips.enums
                              (cond-> []
                                exclude-clause (conj exclude-clause)
                                true (conj '(:require [ol.vips :as v]))))]
    (vec
     (concat
      [ns-form
       (registry-source registry)]

      (map (fn [{:keys [id]}]
             (list 'def (symbol (name id)) (list 'get 'registry id)))
           enum-specs)

      ['(defn enums
          []
          (keys registry))

       '(defn describe
          [enum-id]
          (or (get registry enum-id)
              (throw (ex-info "Unknown generated enum"
                              {:enum-id enum-id}))))

       '(defn encode
          [enum-id value]
          (let [{:keys [type-name]} (describe enum-id)]
            (v/encode-enum type-name value)))

       '(defn decode
          [enum-id value]
          (let [{:keys [type-name]} (describe enum-id)]
            (v/decode-enum type-name value)))]))))

(defn- operation-forms
  [operation-specs]
  (let [registry       (into (sorted-map) (map (juxt :id identity) operation-specs))
        op-symbols     (map (comp symbol name :id) operation-specs)
        exclude-clause (refer-clojure-exclude-clause op-symbols)
        ns-form        (list* 'ns
                              'ol.vips.operations
                              (cond-> []
                                exclude-clause (conj exclude-clause)
                                true (conj '(:require [ol.vips :as v]))))]
    (vec
     (concat
      [ns-form
       (registry-source registry)

       '(defn operations
          []
          (keys registry))

       '(defn describe
          [operation-id]
          (or (get registry operation-id)
              (throw (ex-info "Unknown generated operation"
                              {:operation-id operation-id}))))]

      (map operation-source operation-specs)))))

(defn generate!
  []
  (v/init!)
  (let [{raw-operations :operations
         skipped        :skipped}   (load-operation-infos)
        operations                  (->> raw-operations
                                         (filter operation-supported?)
                                         (map operation-spec)
                                         (sort-by :id)
                                         vec)
        enum-type-names             (->> raw-operations
                                         (filter operation-supported?)
                                         (mapcat :args)
                                         (filter #(= :enum (:kind %)))
                                         (map :value-type)
                                         distinct
                                         sort
                                         vec)
        enums                       (mapv enum-spec enum-type-names)]
    (emit-forms! "src/ol/vips/enums.clj" (enum-forms enums))
    (emit-forms! "src/ol/vips/operations.clj" (operation-forms operations))
    {:enum-count      (count enums)
     :operation-count (count operations)
     :skipped-count   (count skipped)
     :paths           ["src/ol/vips/enums.clj"
                       "src/ol/vips/operations.clj"]}))

(defn -main
  [& _args]
  (let [{:keys [enum-count operation-count skipped-count paths]} (generate!)]
    (println "generated" enum-count "enum defs and" operation-count "operation defs")
    (println "skipped" skipped-count "non-instantiable operations")
    (doseq [path paths]
      (println path))))
