;; Copyright (c) 2026 Casey Link <casey@outskirtslabs.com>
;; SPDX-License-Identifier: EUPL-1.2
;; Generated by `bb gen`. Do not edit by hand.

(ns ol.vips.enums
  "Generated enum descriptors for normalized libvips enum ids.
  
  Use [[registry]] or the generated enum vars to inspect enum metadata. Use [[ol.vips/encode-enum]] and [[ol.vips/decode-enum]] to convert between keywords and the underlying libvips integer values."
  (:refer-clojure :exclude [extend]))

(def registry
  "Generated registry of libvips enum descriptors keyed by normalized enum id."
  {:access                   {:type-name "VipsAccess", :keyword->value {:random 0, :sequential 1, :sequential-unbuffered 2}, :value->keyword {0 :random, 1 :sequential, 2 :sequential-unbuffered}, :id :access, :values [:random :sequential :sequential-unbuffered]}
   :align                    {:type-name "VipsAlign", :keyword->value {:low 0, :centre 1, :high 2}, :value->keyword {0 :low, 1 :centre, 2 :high}, :id :align, :values [:centre :high :low]}
   :angle                    {:type-name "VipsAngle", :keyword->value {:d0 0, :d90 1, :d180 2, :d270 3}, :value->keyword {0 :d0, 1 :d90, 2 :d180, 3 :d270}, :id :angle, :values [:d0 :d180 :d270 :d90]}
   :angle45                  {:type-name "VipsAngle45", :keyword->value {:d0 0, :d45 1, :d90 2, :d135 3, :d180 4, :d225 5, :d270 6, :d315 7}, :value->keyword {0 :d0, 1 :d45, 2 :d90, 3 :d135, 4 :d180, 5 :d225, 6 :d270, 7 :d315}, :id :angle45, :values [:d0 :d135 :d180 :d225 :d270 :d315 :d45 :d90]}
   :band-format              {:type-name "VipsBandFormat", :keyword->value {:notset -1, :double 8, :short 3, :ushort 2, :int 5, :uint 4, :float 6, :complex 7, :dpcomplex 9, :uchar 0, :char 1}, :value->keyword {0 :uchar, 7 :complex, 1 :char, 4 :uint, -1 :notset, 6 :float, 3 :short, 2 :ushort, 9 :dpcomplex, 5 :int, 8 :double}, :id :band-format, :values [:char :complex :double :dpcomplex :float :int :notset :short :uchar :uint :ushort]}
   :blend-mode               {:type-name "VipsBlendMode", :keyword->value {:dest-in 8, :dest-over 7, :screen 15, :darken 17, :colour-dodge 19, :lighten 18, :dest-atop 10, :source 1, :atop 5, :colour-burn 20, :overlay 16, :xor 11, :out 4, :difference 23, :saturate 13, :exclusion 24, :hard-light 21, :multiply 14, :over 2, :add 12, :soft-light 22, :dest 6, :dest-out 9, :in 3, :clear 0}, :value->keyword {0 :clear, 7 :dest-over, 20 :colour-burn, 1 :source, 24 :exclusion, 4 :out, 15 :screen, 21 :hard-light, 13 :saturate, 22 :soft-light, 6 :dest, 17 :darken, 3 :in, 12 :add, 2 :over, 23 :difference, 19 :colour-dodge, 11 :xor, 9 :dest-out, 5 :atop, 14 :multiply, 16 :overlay, 10 :dest-atop, 18 :lighten, 8 :dest-in}, :id :blend-mode, :values [:add :atop :clear :colour-burn :colour-dodge :darken :dest :dest-atop :dest-in :dest-out :dest-over :difference :exclusion :hard-light :in :lighten :multiply :out :over :overlay :saturate :screen :soft-light :source :xor]}
   :coding                   {:type-name "VipsCoding", :keyword->value {:error -1, :none 0, :labq 2, :rad 6}, :value->keyword {-1 :error, 0 :none, 2 :labq, 6 :rad}, :id :coding, :values [:error :labq :none :rad]}
   :combine                  {:type-name "VipsCombine", :keyword->value {:max 0, :sum 1, :min 2}, :value->keyword {0 :max, 1 :sum, 2 :min}, :id :combine, :values [:max :min :sum]}
   :combine-mode             {:type-name "VipsCombineMode", :keyword->value {:set 0, :add 1}, :value->keyword {0 :set, 1 :add}, :id :combine-mode, :values [:add :set]}
   :compass-direction        {:type-name "VipsCompassDirection", :keyword->value {:west 4, :south 3, :north-west 8, :north-east 5, :east 2, :south-west 7, :south-east 6, :north 1, :centre 0}, :value->keyword {0 :centre, 7 :south-west, 1 :north, 4 :west, 6 :south-east, 3 :south, 2 :east, 5 :north-east, 8 :north-west}, :id :compass-direction, :values [:centre :east :north :north-east :north-west :south :south-east :south-west :west]}
   :direction                {:type-name "VipsDirection", :keyword->value {:horizontal 0, :vertical 1}, :value->keyword {0 :horizontal, 1 :vertical}, :id :direction, :values [:horizontal :vertical]}
   :extend                   {:type-name "VipsExtend", :keyword->value {:black 0, :copy 1, :repeat 2, :mirror 3, :white 4, :background 5}, :value->keyword {0 :black, 1 :copy, 2 :repeat, 3 :mirror, 4 :white, 5 :background}, :id :extend, :values [:background :black :copy :mirror :repeat :white]}
   :fail-on                  {:type-name "VipsFailOn", :keyword->value {:none 0, :truncated 1, :error 2, :warning 3}, :value->keyword {0 :none, 1 :truncated, 2 :error, 3 :warning}, :id :fail-on, :values [:error :none :truncated :warning]}
   :foreign-dz-container     {:type-name "VipsForeignDzContainer", :keyword->value {:fs 0, :zip 1, :szi 2}, :value->keyword {0 :fs, 1 :zip, 2 :szi}, :id :foreign-dz-container, :values [:fs :szi :zip]}
   :foreign-dz-depth         {:type-name "VipsForeignDzDepth", :keyword->value {:onepixel 0, :onetile 1, :one 2}, :value->keyword {0 :onepixel, 1 :onetile, 2 :one}, :id :foreign-dz-depth, :values [:one :onepixel :onetile]}
   :foreign-dz-layout        {:type-name "VipsForeignDzLayout", :keyword->value {:dz 0, :zoomify 1, :google 2, :iiif 3, :iiif3 4}, :value->keyword {0 :dz, 1 :zoomify, 2 :google, 3 :iiif, 4 :iiif3}, :id :foreign-dz-layout, :values [:dz :google :iiif :iiif3 :zoomify]}
   :foreign-heif-compression {:type-name "VipsForeignHeifCompression", :keyword->value {:hevc 1, :avc 2, :jpeg 3, :av1 4}, :value->keyword {1 :hevc, 2 :avc, 3 :jpeg, 4 :av1}, :id :foreign-heif-compression, :values [:av1 :avc :hevc :jpeg]}
   :foreign-heif-encoder     {:type-name "VipsForeignHeifEncoder", :keyword->value {:auto 0, :aom 1, :rav1e 2, :svt 3, :x265 4}, :value->keyword {0 :auto, 1 :aom, 2 :rav1e, 3 :svt, 4 :x265}, :id :foreign-heif-encoder, :values [:aom :auto :rav1e :svt :x265]}
   :foreign-subsample        {:type-name "VipsForeignSubsample", :keyword->value {:auto 0, :on 1, :off 2}, :value->keyword {0 :auto, 1 :on, 2 :off}, :id :foreign-subsample, :values [:auto :off :on]}
   :foreign-tiff-compression {:type-name "VipsForeignTiffCompression", :keyword->value {:packbits 3, :ccittfax4 4, :zstd 7, :jp2k 8, :webp 6, :lzw 5, :deflate 2, :jpeg 1, :none 0}, :value->keyword {0 :none, 7 :zstd, 1 :jpeg, 4 :ccittfax4, 6 :webp, 3 :packbits, 2 :deflate, 5 :lzw, 8 :jp2k}, :id :foreign-tiff-compression, :values [:ccittfax4 :deflate :jp2k :jpeg :lzw :none :packbits :webp :zstd]}
   :foreign-tiff-predictor   {:type-name "VipsForeignTiffPredictor", :keyword->value {:none 1, :horizontal 2, :float 3}, :value->keyword {1 :none, 2 :horizontal, 3 :float}, :id :foreign-tiff-predictor, :values [:float :horizontal :none]}
   :foreign-tiff-resunit     {:type-name "VipsForeignTiffResunit", :keyword->value {:cm 0, :inch 1}, :value->keyword {0 :cm, 1 :inch}, :id :foreign-tiff-resunit, :values [:cm :inch]}
   :foreign-webp-preset      {:type-name "VipsForeignWebpPreset", :keyword->value {:default 0, :picture 1, :photo 2, :drawing 3, :icon 4, :text 5}, :value->keyword {0 :default, 1 :picture, 2 :photo, 3 :drawing, 4 :icon, 5 :text}, :id :foreign-webp-preset, :values [:default :drawing :icon :photo :picture :text]}
   :intent                   {:type-name "VipsIntent", :keyword->value {:perceptual 0, :relative 1, :saturation 2, :absolute 3, :auto 32}, :value->keyword {0 :perceptual, 1 :relative, 2 :saturation, 3 :absolute, 32 :auto}, :id :intent, :values [:absolute :auto :perceptual :relative :saturation]}
   :interesting              {:type-name "VipsInteresting", :keyword->value {:none 0, :centre 1, :entropy 2, :attention 3, :low 4, :high 5, :all 6}, :value->keyword {0 :none, 1 :centre, 2 :entropy, 3 :attention, 4 :low, 5 :high, 6 :all}, :id :interesting, :values [:all :attention :centre :entropy :high :low :none]}
   :interpretation           {:type-name "VipsInterpretation", :keyword->value {:xyz 12, :lab 13, :labs 21, :histogram 10, :fourier 24, :srgb 22, :grey16 26, :rgb 17, :cmyk 15, :hsv 29, :scrgb 28, :cmc 18, :matrix 27, :lch 19, :rgb16 25, :multiband 0, :error -1, :yxy 23, :labq 16, :b-w 1}, :value->keyword {0 :multiband, 27 :matrix, 1 :b-w, 24 :fourier, -1 :error, 15 :cmyk, 21 :labs, 13 :lab, 22 :srgb, 29 :hsv, 28 :scrgb, 25 :rgb16, 17 :rgb, 12 :xyz, 23 :yxy, 19 :lch, 26 :grey16, 16 :labq, 10 :histogram, 18 :cmc}, :id :interpretation, :values [:b-w :cmc :cmyk :error :fourier :grey16 :histogram :hsv :lab :labq :labs :lch :matrix :multiband :rgb :rgb16 :scrgb :srgb :xyz :yxy]}
   :kernel                   {:type-name "VipsKernel", :keyword->value {:nearest 0, :linear 1, :cubic 2, :mitchell 3, :lanczos2 4, :lanczos3 5, :mks2013 6, :mks2021 7}, :value->keyword {0 :nearest, 1 :linear, 2 :cubic, 3 :mitchell, 4 :lanczos2, 5 :lanczos3, 6 :mks2013, 7 :mks2021}, :id :kernel, :values [:cubic :lanczos2 :lanczos3 :linear :mitchell :mks2013 :mks2021 :nearest]}
   :operation-boolean        {:type-name "VipsOperationBoolean", :keyword->value {:and 0, :or 1, :eor 2, :lshift 3, :rshift 4}, :value->keyword {0 :and, 1 :or, 2 :eor, 3 :lshift, 4 :rshift}, :id :operation-boolean, :values [:and :eor :lshift :or :rshift]}
   :operation-complex        {:type-name "VipsOperationComplex", :keyword->value {:polar 0, :rect 1, :conj 2}, :value->keyword {0 :polar, 1 :rect, 2 :conj}, :id :operation-complex, :values [:conj :polar :rect]}
   :operation-complex2       {:type-name "VipsOperationComplex2", :keyword->value {:cross-phase 0}, :value->keyword {0 :cross-phase}, :id :operation-complex2, :values [:cross-phase]}
   :operation-complexget     {:type-name "VipsOperationComplexget", :keyword->value {:real 0, :imag 1}, :value->keyword {0 :real, 1 :imag}, :id :operation-complexget, :values [:imag :real]}
   :operation-math           {:type-name "VipsOperationMath", :keyword->value {:atan 5, :cos 1, :log10 7, :tan 2, :exp 8, :acosh 14, :cosh 11, :asin 3, :sinh 10, :atanh 15, :sin 0, :acos 4, :asinh 13, :log 6, :exp10 9, :tanh 12}, :value->keyword {0 :sin, 7 :log10, 1 :cos, 4 :acos, 15 :atanh, 13 :asinh, 6 :log, 3 :asin, 12 :tanh, 2 :tan, 11 :cosh, 9 :exp10, 5 :atan, 14 :acosh, 10 :sinh, 8 :exp}, :id :operation-math, :values [:acos :acosh :asin :asinh :atan :atanh :cos :cosh :exp :exp10 :log :log10 :sin :sinh :tan :tanh]}
   :operation-math2          {:type-name "VipsOperationMath2", :keyword->value {:pow 0, :wop 1, :atan2 2}, :value->keyword {0 :pow, 1 :wop, 2 :atan2}, :id :operation-math2, :values [:atan2 :pow :wop]}
   :operation-morphology     {:type-name "VipsOperationMorphology", :keyword->value {:erode 0, :dilate 1}, :value->keyword {0 :erode, 1 :dilate}, :id :operation-morphology, :values [:dilate :erode]}
   :operation-relational     {:type-name "VipsOperationRelational", :keyword->value {:equal 0, :noteq 1, :less 2, :lesseq 3, :more 4, :moreeq 5}, :value->keyword {0 :equal, 1 :noteq, 2 :less, 3 :lesseq, 4 :more, 5 :moreeq}, :id :operation-relational, :values [:equal :less :lesseq :more :moreeq :noteq]}
   :operation-round          {:type-name "VipsOperationRound", :keyword->value {:rint 0, :ceil 1, :floor 2}, :value->keyword {0 :rint, 1 :ceil, 2 :floor}, :id :operation-round, :values [:ceil :floor :rint]}
   :pcs                      {:type-name "VipsPCS", :keyword->value {:lab 0, :xyz 1}, :value->keyword {0 :lab, 1 :xyz}, :id :pcs, :values [:lab :xyz]}
   :precision                {:type-name "VipsPrecision", :keyword->value {:integer 0, :float 1, :approximate 2}, :value->keyword {0 :integer, 1 :float, 2 :approximate}, :id :precision, :values [:approximate :float :integer]}
   :region-shrink            {:type-name "VipsRegionShrink", :keyword->value {:mean 0, :median 1, :mode 2, :max 3, :min 4, :nearest 5}, :value->keyword {0 :mean, 1 :median, 2 :mode, 3 :max, 4 :min, 5 :nearest}, :id :region-shrink, :values [:max :mean :median :min :mode :nearest]}
   :sdf-shape                {:type-name "VipsSdfShape", :keyword->value {:circle 0, :box 1, :rounded-box 2, :line 3}, :value->keyword {0 :circle, 1 :box, 2 :rounded-box, 3 :line}, :id :sdf-shape, :values [:box :circle :line :rounded-box]}
   :size                     {:type-name "VipsSize", :keyword->value {:both 0, :up 1, :down 2, :force 3}, :value->keyword {0 :both, 1 :up, 2 :down, 3 :force}, :id :size, :values [:both :down :force :up]}
   :text-wrap                {:type-name "VipsTextWrap", :keyword->value {:word 0, :char 1, :word-char 2, :none 3}, :value->keyword {0 :word, 1 :char, 2 :word-char, 3 :none}, :id :text-wrap, :values [:char :none :word :word-char]}})

(def access
  "Generated enum descriptor for `VipsAccess`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:random`
  - `:sequential`
  - `:sequential-unbuffered`"
  (get registry :access))

(def align
  "Generated enum descriptor for `VipsAlign`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:centre`
  - `:high`
  - `:low`"
  (get registry :align))

(def angle
  "Generated enum descriptor for `VipsAngle`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:d0`
  - `:d180`
  - `:d270`
  - `:d90`"
  (get registry :angle))

(def angle45
  "Generated enum descriptor for `VipsAngle45`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:d0`
  - `:d135`
  - `:d180`
  - `:d225`
  - `:d270`
  - `:d315`
  - `:d45`
  - `:d90`"
  (get registry :angle45))

(def band-format
  "Generated enum descriptor for `VipsBandFormat`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:char`
  - `:complex`
  - `:double`
  - `:dpcomplex`
  - `:float`
  - `:int`
  - `:notset`
  - `:short`
  - `:uchar`
  - `:uint`
  - `:ushort`"
  (get registry :band-format))

(def blend-mode
  "Generated enum descriptor for `VipsBlendMode`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:add`
  - `:atop`
  - `:clear`
  - `:colour-burn`
  - `:colour-dodge`
  - `:darken`
  - `:dest`
  - `:dest-atop`
  - `:dest-in`
  - `:dest-out`
  - `:dest-over`
  - `:difference`
  - `:exclusion`
  - `:hard-light`
  - `:in`
  - `:lighten`
  - `:multiply`
  - `:out`
  - `:over`
  - `:overlay`
  - `:saturate`
  - `:screen`
  - `:soft-light`
  - `:source`
  - `:xor`"
  (get registry :blend-mode))

(def coding
  "Generated enum descriptor for `VipsCoding`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:error`
  - `:labq`
  - `:none`
  - `:rad`"
  (get registry :coding))

(def combine
  "Generated enum descriptor for `VipsCombine`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:max`
  - `:min`
  - `:sum`"
  (get registry :combine))

(def combine-mode
  "Generated enum descriptor for `VipsCombineMode`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:add`
  - `:set`"
  (get registry :combine-mode))

(def compass-direction
  "Generated enum descriptor for `VipsCompassDirection`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:centre`
  - `:east`
  - `:north`
  - `:north-east`
  - `:north-west`
  - `:south`
  - `:south-east`
  - `:south-west`
  - `:west`"
  (get registry :compass-direction))

(def direction
  "Generated enum descriptor for `VipsDirection`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:horizontal`
  - `:vertical`"
  (get registry :direction))

(def extend
  "Generated enum descriptor for `VipsExtend`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:background`
  - `:black`
  - `:copy`
  - `:mirror`
  - `:repeat`
  - `:white`"
  (get registry :extend))

(def fail-on
  "Generated enum descriptor for `VipsFailOn`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:error`
  - `:none`
  - `:truncated`
  - `:warning`"
  (get registry :fail-on))

(def foreign-dz-container
  "Generated enum descriptor for `VipsForeignDzContainer`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:fs`
  - `:szi`
  - `:zip`"
  (get registry :foreign-dz-container))

(def foreign-dz-depth
  "Generated enum descriptor for `VipsForeignDzDepth`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:one`
  - `:onepixel`
  - `:onetile`"
  (get registry :foreign-dz-depth))

(def foreign-dz-layout
  "Generated enum descriptor for `VipsForeignDzLayout`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:dz`
  - `:google`
  - `:iiif`
  - `:iiif3`
  - `:zoomify`"
  (get registry :foreign-dz-layout))

(def foreign-heif-compression
  "Generated enum descriptor for `VipsForeignHeifCompression`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:av1`
  - `:avc`
  - `:hevc`
  - `:jpeg`"
  (get registry :foreign-heif-compression))

(def foreign-heif-encoder
  "Generated enum descriptor for `VipsForeignHeifEncoder`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:aom`
  - `:auto`
  - `:rav1e`
  - `:svt`
  - `:x265`"
  (get registry :foreign-heif-encoder))

(def foreign-subsample
  "Generated enum descriptor for `VipsForeignSubsample`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:auto`
  - `:off`
  - `:on`"
  (get registry :foreign-subsample))

(def foreign-tiff-compression
  "Generated enum descriptor for `VipsForeignTiffCompression`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:ccittfax4`
  - `:deflate`
  - `:jp2k`
  - `:jpeg`
  - `:lzw`
  - `:none`
  - `:packbits`
  - `:webp`
  - `:zstd`"
  (get registry :foreign-tiff-compression))

(def foreign-tiff-predictor
  "Generated enum descriptor for `VipsForeignTiffPredictor`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:float`
  - `:horizontal`
  - `:none`"
  (get registry :foreign-tiff-predictor))

(def foreign-tiff-resunit
  "Generated enum descriptor for `VipsForeignTiffResunit`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:cm`
  - `:inch`"
  (get registry :foreign-tiff-resunit))

(def foreign-webp-preset
  "Generated enum descriptor for `VipsForeignWebpPreset`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:default`
  - `:drawing`
  - `:icon`
  - `:photo`
  - `:picture`
  - `:text`"
  (get registry :foreign-webp-preset))

(def intent
  "Generated enum descriptor for `VipsIntent`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:absolute`
  - `:auto`
  - `:perceptual`
  - `:relative`
  - `:saturation`"
  (get registry :intent))

(def interesting
  "Generated enum descriptor for `VipsInteresting`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:all`
  - `:attention`
  - `:centre`
  - `:entropy`
  - `:high`
  - `:low`
  - `:none`"
  (get registry :interesting))

(def interpretation
  "Generated enum descriptor for `VipsInterpretation`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:b-w`
  - `:cmc`
  - `:cmyk`
  - `:error`
  - `:fourier`
  - `:grey16`
  - `:histogram`
  - `:hsv`
  - `:lab`
  - `:labq`
  - `:labs`
  - `:lch`
  - `:matrix`
  - `:multiband`
  - `:rgb`
  - `:rgb16`
  - `:scrgb`
  - `:srgb`
  - `:xyz`
  - `:yxy`"
  (get registry :interpretation))

(def kernel
  "Generated enum descriptor for `VipsKernel`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:cubic`
  - `:lanczos2`
  - `:lanczos3`
  - `:linear`
  - `:mitchell`
  - `:mks2013`
  - `:mks2021`
  - `:nearest`"
  (get registry :kernel))

(def operation-boolean
  "Generated enum descriptor for `VipsOperationBoolean`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:and`
  - `:eor`
  - `:lshift`
  - `:or`
  - `:rshift`"
  (get registry :operation-boolean))

(def operation-complex
  "Generated enum descriptor for `VipsOperationComplex`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:conj`
  - `:polar`
  - `:rect`"
  (get registry :operation-complex))

(def operation-complex2
  "Generated enum descriptor for `VipsOperationComplex2`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:cross-phase`"
  (get registry :operation-complex2))

(def operation-complexget
  "Generated enum descriptor for `VipsOperationComplexget`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:imag`
  - `:real`"
  (get registry :operation-complexget))

(def operation-math
  "Generated enum descriptor for `VipsOperationMath`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:acos`
  - `:acosh`
  - `:asin`
  - `:asinh`
  - `:atan`
  - `:atanh`
  - `:cos`
  - `:cosh`
  - `:exp`
  - `:exp10`
  - `:log`
  - `:log10`
  - `:sin`
  - `:sinh`
  - `:tan`
  - `:tanh`"
  (get registry :operation-math))

(def operation-math2
  "Generated enum descriptor for `VipsOperationMath2`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:atan2`
  - `:pow`
  - `:wop`"
  (get registry :operation-math2))

(def operation-morphology
  "Generated enum descriptor for `VipsOperationMorphology`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:dilate`
  - `:erode`"
  (get registry :operation-morphology))

(def operation-relational
  "Generated enum descriptor for `VipsOperationRelational`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:equal`
  - `:less`
  - `:lesseq`
  - `:more`
  - `:moreeq`
  - `:noteq`"
  (get registry :operation-relational))

(def operation-round
  "Generated enum descriptor for `VipsOperationRound`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:ceil`
  - `:floor`
  - `:rint`"
  (get registry :operation-round))

(def pcs
  "Generated enum descriptor for `VipsPCS`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:lab`
  - `:xyz`"
  (get registry :pcs))

(def precision
  "Generated enum descriptor for `VipsPrecision`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:approximate`
  - `:float`
  - `:integer`"
  (get registry :precision))

(def region-shrink
  "Generated enum descriptor for `VipsRegionShrink`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:max`
  - `:mean`
  - `:median`
  - `:min`
  - `:mode`
  - `:nearest`"
  (get registry :region-shrink))

(def sdf-shape
  "Generated enum descriptor for `VipsSdfShape`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:box`
  - `:circle`
  - `:line`
  - `:rounded-box`"
  (get registry :sdf-shape))

(def size
  "Generated enum descriptor for `VipsSize`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:both`
  - `:down`
  - `:force`
  - `:up`"
  (get registry :size))

(def text-wrap
  "Generated enum descriptor for `VipsTextWrap`.
  
  Use this value directly or look it up in [[registry]] when you want the generated enum map.
  
  Known values:
  - `:char`
  - `:none`
  - `:word`
  - `:word-char`"
  (get registry :text-wrap))

(defn enums "Lists the generated libvips enum ids." [] (keys registry))

